### ISSUE TITLE
Remove stdint.h to enable build with VC++ 9.0 (VS2008) if it is unnecessary

### ISSUE THREAD

**Issue by sakurai-youhei** [fancycode/MemoryModule#45]
If `stdint.h` in [MemoryModule.c](https://github.com/fancycode/MemoryModule/blob/v0_0_4/MemoryModule.c#L42) is unnecessary, it is nice to remove it to enable build with VC++ 9.0 (VS2008) which is still actively used by Python 2.7.

I'm building and roughly testing MemoryModule with removing the `stdint.h` and it seems to work without problem on VC++ 9.0, 10.0 and 14.0.

**Compilation of MemoryModule (no `stdint.h`) with VC++ 9.0 32bit**
https://ci.appveyor.com/project/sakurai_youhei/pymemorymodule/build/25/job/shv70h2w1pfxbakv#L79

**Compilation of MemoryModule (no `stdint.h`) with VC++ 9.0 64bit**
https://ci.appveyor.com/project/sakurai_youhei/pymemorymodule/build/25/job/lac6j3tgcupiruyr#L85

**Comment by fancycode** [comment]
Could you please create this as pull request so it can be automatically CI tested?
