### ISSUE TITLE
Is it possible to load a library from memory instead of from the file system on Linux?

### ISSUE THREAD

**Issue by YumingMa** [fancycode/MemoryModule#77]
Dear,

Does MemoryModule only work on Windows?  if yes, How to work on Linux? Can you recommend  a good idea? Thanks in advenced!

**Comment by ianhbell** [comment]
See dlmopen: https://docs.oracle.com/cd/E19455-01/806-0627/6j9vhfmos/index.html

**Comment by Coldzer0** [comment]
@YumingMa 
see this 
https://x-c3ll.github.io/posts/fileless-memfd_create/
