### ISSUE TITLE
Use Unicode version of LoadLibrary

### ISSUE THREAD

**Issue by Fr0sT-Brutal** [fancycode/MemoryModule#90]
Currently ANSI version `LoadLibraryA` is used which could fail to load libs with non-latin chars in name

**Comment by Elmue** [comment]
You did not study the code before writing this.
LoadLibraryA() is called with a DLL name which comes from IMAGE_IMPORT_DESCRIPTOR.
The 'Name' field in this structure points to an ASCII string.
So a Unicode version does not make any sense.

**Comment by Fr0sT-Brutal** [comment]
Ah yes, sure. Sorry for false alert :-[
